---
- hosts: all
  name: Add cis-92 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - php
          - apache2
          - php-xml

- name: Ansible Copy Example Local to Remote
  hosts: all
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: /home/ang2693/cis-91/dokuwiki/backup
        dest: /etc/cron.hourly
        owner: root
        group: root        
        mode: 0644